### ISSUE TITLE
Не работает.

### ISSUE THREAD

**Issue by siksof** [KorshukAleksey/Slaves-Vk-MiniApp#1]
ERROR:web_contents_delegate.cc(217)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.

PS. Ещё он не работает с двухэтапкой.

**Comment by AlekseyKorshuk** [comment]
> ERROR:web_contents_delegate.cc(217)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
> 
> PS. Ещё он не работает с двухэтапкой.

Updated. New version without webdriver is avaliable now. README coming soon 🤗
