### ISSUE TITLE
Не запускается.

### ISSUE THREAD

**Issue by siksof** [KorshukAleksey/Slaves-Vk-MiniApp#2]
Traceback (most recent call last):
  File "main.py", line 178, in <module>
    tops = list(topUsers()['list'])
KeyError: 'list'

2. Добавь пожалуйста requirements.txt чтобы можно было сразу понять каких пипов не хватает для запуска. Потому что если запускать сразу через лкм, то окно питона крашит и чтобы понять чего не хватает приходится запускать через vs code.

**Comment by InquisitorSpyke** [comment]
И что делать кстати?

**Comment by siksof** [comment]
> И что делать кстати?

Пока что без понятия. Пробовал что-то сам сделать, но кажется, тут проблема где-то в работе с API.
Не понятно вообще какой ключ авторизации нужен. Как я понял, это ключ API авторизации от странице.
Ждём ответа кодера вообщем.

**Comment by InquisitorSpyke** [comment]
Понял принял.

**Comment by InquisitorSpyke** [comment]
Еще остаются вопросы об фразе "Get your authorization". Это нужен токен или что-то другое? Еще бы однозначно понимать, как это токен доставать.

**Comment by siksof** [comment]
> Еще остаются вопросы об фразе "Get your authorization". Это нужен токен или что-то другое? Еще бы однозначно понимать, как это токен доставать.

У меня столько же инфы об этом репозитории сколько и у тебя. Тут не нашёл инфы какой именно токен нежен.

**Comment by InquisitorSpyke** [comment]
Ну это я сразу вопрос задал для Автора.

**Comment by LikeKey1** [comment]
KeyError: 'list' возникает из-за того, что в json возвращается одна лишь строка error, с авторизацией либо что-то не то, либо с  апи

**Comment by InquisitorSpyke** [comment]
А у вас работает?

> KeyError: 'list' возникает из-за того, что в json возвращается одна лишь строка error, с авторизацией либо что-то не то, либо с апи

**Comment by LikeKey1** [comment]
нет

**Comment by InquisitorSpyke** [comment]
еще я так понимаю в 178 строчке скобки неправильно стоят

**Comment by LikeKey1** [comment]
не знаю, я не программирую на питоне

**Comment by LikeKey1** [comment]
вроде правильно все стоит

**Comment by LikeKey1** [comment]
есть вообще ссылка на документацию по используемому апи?

**Comment by InquisitorSpyke** [comment]
все, я понял. Ошибся

**Comment by MrFurison** [comment]
> еще я так понимаю в 178 строчке скобки неправильно стоят
> 

Там от скобок не менялось ничего.

**Comment by MrFurison** [comment]
> есть вообще ссылка на документацию по используемому апи?
> 

Для начала бы услышать от разраба какой именно апи токен нужен. Я брал отсюда https://vkhost.github.io/ (vk api)

**Comment by MrFurison** [comment]
> KeyError: 'list' возникает из-за того, что в json возвращается одна лишь строка error, с авторизацией либо что-то не то, либо с  апи

Json вообще нету в репе и сам код его не создаёт.
Я создавал list.json, но тоже мимо.

**Comment by InquisitorSpyke** [comment]
Жалко разраб не здесь(9((

**Comment by AlekseyKorshuk** [comment]
Я тут. Скоро выкачу инструкцию. А код авторизации это не совсем api. Ждите 🤗

**Comment by AlekseyKorshuk** [comment]
И у вас не работает из-за отсутствия это самого ключа.

**Comment by InquisitorSpyke** [comment]
А я то думаю, почему нельзя было вместо слова авторизация, написать token

**Comment by InquisitorSpyke** [comment]
![1563534222172367760](https://user-images.githubusercontent.com/19300061/112265062-67448100-8ca4-11eb-8676-3018ba803c35.jpg)

**Comment by InquisitorSpyke** [comment]
мы

**Comment by InquisitorSpyke** [comment]
Ждем тогда


> Я тут. Скоро выкачу инструкцию. А код авторизации это не совсем api. Ждите 🤗

**Comment by InquisitorSpyke** [comment]
Вроде апдейт, а вроде не понятно, кто такая "авторизация" ваша.

**Comment by AlekseyKorshuk** [comment]
Обновил. Следуйте инструкциям из README.

**Comment by LikeKey1** [comment]
![image](https://user-images.githubusercontent.com/59282789/112274345-b947cf80-8cc1-11eb-943f-78319ea5adfc.png)
что это выводит?

**Comment by AlekseyKorshuk** [comment]
Если что-то не понятно - пишите. Ошибки - создавайте Issues.

**Comment by MrFurison** [comment]
> ![image](https://user-images.githubusercontent.com/59282789/112274345-b947cf80-8cc1-11eb-943f-78319ea5adfc.png)
> что это выводит?
> 

Твой id и сколько у тебя рабов

**Comment by AlekseyKorshuk** [comment]
Нет

**Comment by LikeKey1** [comment]
это не мой id

**Comment by AlekseyKorshuk** [comment]
Он ищет рабов для покупки из топов.
Рекурсивно*

**Comment by LikeKey1** [comment]
а окей

**Comment by AlekseyKorshuk** [comment]
Фичи бота я напишу чуть позже тоже в ридми

**Comment by AlekseyKorshuk** [comment]
Я закрываю этот топик

**Comment by MrFurison** [comment]
А вот .exe мне уже не нравится, не внушает доверия. И как теперь проверить на снитчеры?

**Comment by InquisitorSpyke** [comment]
> А вот .exe мне уже не нравится, не внушает доверия. И как теперь проверить на снитчеры?

Кстати да.
Печально то, что исходник пропал.
